### ISSUE TITLE
'NoneType' object is not subscriptable, xmlplain.xml_from_obj

### ISSUE THREAD

**Issue by sumits99** [guillon/xmlplain#3]
dict to xml failed..
xml=xmlplain.xml_from_obj(dictionary)

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ssrivastava02/Desktop/scriptRepo/yaml_utils/venv/lib/python3.8/site-packages/xmlplain.py", line 556, in xml_from_obj
    return xml_from_events(events, outf, encoding=encoding, process_content=process_content)
  File "/Users/ssrivastava02/Desktop/scriptRepo/yaml_utils/venv/lib/python3.8/site-packages/xmlplain.py", line 275, in xml_from_events
    for evt in events: generator.append(evt)
  File "/Users/ssrivastava02/Desktop/scriptRepo/yaml_utils/venv/lib/python3.8/site-packages/xmlplain.py", line 231, in append
    self.start[1][value[0]] = value[1]
TypeError: 'NoneType' object is not subscriptable

**Comment by 6b6279** [comment]
Hello,

I had a similar issue with an internal project using xmlplain. Turns out the XMI file, which I was using, was malformed. Check out the `append` function of `SaxGenerator`. See if there is an issue regarding the tokens expected by `append`. I doubt that your problem is caused directly by xmlplain.

**Comment by guillon** [comment]
@sumits99 optionally, could you attach an example input (the content of your dictionnary variable, or s stripped down version) producing the issue?
